{% set name = "marshmallow-sqlalchemy" %}
{% set version = "1.4.2" %}
{% set sha256 = "6410304bf98ec26ea35f3f9d3cee82e51fd093c434612add32a0bdcdb5668f7c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core
  run:
    - python >={{ python_min }}
    - marshmallow >=2.15.2
    - sqlalchemy >=1.2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - marshmallow_sqlalchemy

about:
  home: https://github.com/marshmallow-code/marshmallow-sqlalchemy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SQLAlchemy integration with marshmallow

  description: |
    SQLAlchemy integration with the marshmallow (de)serialization library.
  doc_url: http://marshmallow-sqlalchemy.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/marshmallow-sqlalchemy

extra:
  recipe-maintainers:
    - frol
    - mediocretech
