{% set name = "marshmallow-sqlalchemy" %}
{% set version = "0.18.0" %}
{% set sha256 = "6698354f882919fb232e881bb6f99bdf8a86a76a709105bff826551f53c0b6c5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - marshmallow >=2.0.0
    - sqlalchemy >=0.9.7

test:
  imports:
    - marshmallow_sqlalchemy

about:
  home: https://github.com/marshmallow-code/marshmallow-sqlalchemy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SQLAlchemy integration with marshmallow'

  description: |
    SQLAlchemy integration with the marshmallow (de)serialization library.
  doc_url: http://marshmallow-sqlalchemy.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/marshmallow-sqlalchemy

extra:
  recipe-maintainers:
    - frol
    - igortg
