{% set name = "marshmallow-sqlalchemy" %}
{% set version = "0.17.0" %}
{% set sha256 = "d662fc8103a06b59aafbc33c8ab4f1318799d66aae4f660c1e7e278bc45ef69e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - marshmallow >=2.0.0
    - sqlalchemy >=0.9.7

test:
  imports:
    - marshmallow_sqlalchemy

about:
  home: https://github.com/marshmallow-code/marshmallow-sqlalchemy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SQLAlchemy integration with marshmallow'

  description: |
    SQLAlchemy integration with the marshmallow (de)serialization library.
  doc_url: http://marshmallow-sqlalchemy.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/marshmallow-sqlalchemy

extra:
  recipe-maintainers:
    - frol
    - igortg
