{% set name = "marshmallow-sqlalchemy" %}
{% set version = "0.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/marshmallow-sqlalchemy-{{ version }}.tar.gz
  sha256: 3523a774390ef0c1c0f7c708a7519809c5396cf608720f14f55c36f74ff5bbec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - marshmallow >=3.0.0
    - sqlalchemy >=1.4.40,<3.0
    - packaging >=21.3

test:
  imports:
    - marshmallow_sqlalchemy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marshmallow-code/marshmallow-sqlalchemy
  summary: SQLAlchemy integration with the marshmallow (de)serialization library
  license_family: MIT
  license: MIT
  license_file: LICENSE
  description: |
    SQLAlchemy integration with the marshmallow (de)serialization library.
  doc_url: http://marshmallow-sqlalchemy.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/marshmallow-sqlalchemy

extra:
  recipe-maintainers:
    - frol
    - rxm7706
