travis:
  secure:
    BINSTAR_TOKEN: BczGfL4TurruMZH7a0LVykAVVAsvPPn1EBxESE3gzbjr0YI8JmDvGBaW4sa6OPbtIMdTcNDz1D28qUn5abwr06o69de0KapulWkf2ZatZDGcvRBTx5on7Z08ceCRHMTxoMJhPtJn/ZpX+g+qxIG4wGFhcCwPXUkiPrtlFYMkqr6b5+vdI6Tj7V03l0XS6WEBR+WaqSFhmh5PllXRkHF6x9Xv88CPcU4c+HjfBBLizqxQzStko4oA0Jw3/l8nYAGT+b1IhQkWYYxweETPOk1i2nC9omveWu0f6fo56Be28z8H9zZZ9Zi20gAIWzIQFAAx8AnU27/P9IFYDe848HeTsnIoULmuhkJGN2gkn89X1Ykyo11kQhseUWgRr8toeDNEhjlYPszKpHqTk+McKgR/pWp5ix/nUzKPbFXn2yvzwump8nzrbfXEVDehIOct6d1QPq4H4/Wb4Hq+vVb8Q7hU6w8CBcefv0tmBSRM9JtBvZIv1nY6UOzsKNlKlnbMwaFe5oDls7MfDR8l3Weqer4llti/ujzonVAI+c2QZxZIBztwQMrhtVTiP5cKZq74RF6aaLNzpUYUEgUEbPN3jIrAn5UmcxJ8IuofkkKHKBZpTURp/Pzx1m5pHwf0qezWj1HKzNcoSsep2gpJj8ABsFkOMPpsLaPKvUaDoMyZdzCsguM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
